config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :admins, skip: [:registration]

  namespace :website do
    get  'welcome/index'
    get  'search', to: 'search#questions'
    get  'subject/:subject_id', to: 'search#subject', as: 'search_subject' 
    post 'answer', to: 'answer#question'
  end
  namespace :users_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
  end
  namespace :admins_backoffice do
    get 'welcome/index'
    resources :admins    # Administradores
    resources :subjects  # Assuntos
    resources :questions # Questões
  end

  get 'inicio', to: 'website/welcome#index'
  get 'admin', to: 'admins_backoffice/welcome#index'

  root to: 'website/welcome#index'
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :questions
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :verify_password, only: [:update]
  before_action :set_admin, only: [:update, :edit, :destroy]

  def index
    @admins = Admin.all.page(params[:page]).per(5)
  end

  def edit
  end

  def new 
    @admin = Admin.new
  end

  def create
    @admin = Admin.create(params_admin)
    if @admin.save()
      redirect_to admins_backoffice_admins_path, notice: "Administrador cadastrado com sucesso!"
    else
      render :edit
    end
  end

  def update    
    if @admin.update(params_admin)
      redirect_to admins_backoffice_admins_path, notice: "Administrador atualizado com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    email = @admin.email
    if @admin.destroy
      redirect_to admins_backoffice_admins_path, notice: "Administrador #{email} deletado com sucesso!"
    else
      render :index
    end
  end

  private

  def params_admin
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end

  def verify_password
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end

  def set_admin
    @admin = Admin.find(params[:id])
  end
end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
    before_action :set_question, only: [:update, :edit, :destroy]
    before_action :set_subjects, only: [:edit, :new]
  
    def index
      @questions = Question.includes(:subject)
                           .page(params[:page])
                           .per(5)
    end
  
    def edit
    end
  
    def new 
      @question = Question.new
    end
  
    def create
      @question = Question.create(params_question)
      if @question.save()
        redirect_to admins_backoffice_questions_path, notice: "Questão cadastrada com sucesso!"
      else
        render :edit
      end
    end
  
    def update    
      if @question.update(params_question)
        redirect_to admins_backoffice_questions_path, notice: "Questão atualizada com sucesso!"
      else
        render :edit
      end
    end
  
    def destroy
      if @question.destroy
        redirect_to admins_backoffice_questions_path, notice: "Questão deletada com sucesso!"
      else
        render :index
      end
    end
  
    private
  
    def params_question
      params.require(:question).permit(:description, :subject_id, 
         answers_attributes: [:id, :description, :correct, :_destroy])
    end
  
  
    def set_question
      @question = Question.find(params[:id])
    end

    def set_subjects
      @subjects = Subject.all
    end
  end
  

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
    before_action :set_subject, only: [:update, :edit, :destroy]
  
    def index
      @subjects = Subject.all.page(params[:page]).per(5)
    end
  
    def edit
    end
  
    def new 
      @subject = Subject.new
    end
  
    def create
      @subject = Subject.create(params_subject)
      if @subject.save()
        redirect_to admins_backoffice_subjects_path, notice: "Assunto cadastrado com sucesso!"
      else
        render :edit
      end
    end
  
    def update    
      if @subject.update(params_subject)
        redirect_to admins_backoffice_subjects_path, notice: "Assunto atualizado com sucesso!"
      else
        render :edit
      end
    end
  
    def destroy
      if @subject.destroy
        redirect_to admins_backoffice_subjects_path, notice: "Assunto deletado com sucesso!"
      else
        render :index
      end
    end
  
    private
  
    def params_subject
      params.require(:subject).permit(:description)
    end
  
  
    def set_subject
      @subject = Subject.find(params[:id])
    end
  end
  

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout 'admins_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
    def translate_attribute(object = nil, method = nil)
        if object && method
            object.model.human_attribute_name(method)
        else
            '--'
        end
    end
end

app/views/admins_backoffice/subjects/edit.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form', 
           locals: { action_message: 'Editar' } %>

app/views/admins_backoffice/subjects/index.html.erb
<h3>
  <%= t('messages.features.listing', 
      model: @subjects.model_name.human(count: 2)).capitalize %>
</h3>

<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to 'Página inicial', admins_backoffice_welcome_index_path  %>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
      <%= @subjects.model_name.human(count: 2) %>
    </li>
  </ol>
</nav>

<div class="d-flex justify-content-end">
  <%= link_to new_admins_backoffice_subject_path, class: 'btn btn-custom' do %>
    <%= render_svg('add') %> Adicionar
  <% end %>
</div>

<table class="table table-sm">
  <thead>
    <tr>
      <th scope="col"><%= translate_attribute(@subjects, :id) %></th>
      <th scope="col"><%= translate_attribute(@subjects, :description) %></th>
      <th></th>
    </tr>
  </thead>
  
  <tbody>

    <% @subjects.each do |subject| %>

      <tr>
        <td><%= subject.id %></td>
        <td>
          <%= subject.description %>
        </td>
        <td>
          <div class="d-flex justify-content-end gap-1">
            <div 
              data-bs-toggle="tooltip" 
              data-bs-placement="bottom" 
              data-bs-title="Editar">
              <%= link_to edit_admins_backoffice_subject_path(subject), class: "btn btn-circle btn-light" do %>
                <%= render_svg('edit_note') %>
              <% end %>
            </div>
            <div 
              data-bs-toggle="tooltip" 
              data-bs-placement="bottom" 
              data-bs-title="Apagar">
              <%= link_to admins_backoffice_subject_path(subject), class: "btn btn-circle btn-danger", method: :delete, data: { confirm: t('messages.confirm.delete', item: subject.description.truncate(20)) } do %>
                <%= render_svg('delete') %>
              <% end %>
            </div>
          </div>
        </td>
      </tr>

    <% end %>

  </tbody>
</table>

<div class="d-flex justify-content-center">
  <%= paginate @subjects %>
</div>

app/views/admins_backoffice/subjects/new.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form',
           locals: { action_message: 'Novo' } %>