config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :admins, skip: [:registration]

  namespace :website do
    get  'welcome/index'
    get  'search', to: 'search#questions'
    get  'subject/:subject_id', to: 'search#subject', as: 'search_subject' 
    post 'answer', to: 'answer#question'
  end
  namespace :users_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
  end
  namespace :admins_backoffice do
    get 'welcome/index'
    resources :admins    # Administradores
    resources :subjects  # Assuntos
    resources :questions # Questões
  end

  get 'inicio', to: 'website/welcome#index'
  get 'admin', to: 'admins_backoffice/welcome#index'

  root to: 'website/welcome#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject, counter_cache: true, inverse_of: :questions
  has_many :answers
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true

  scope :_search_term_, ->(term, page, per = 10) {
    where('lower(description) LIKE ?', "%#{term.downcase}%")
    .page(page)
    .per(per)
  }

  scope :_search_subject_, ->(subject_id, page, per = 10) {
    where(subject_id: subject_id)
    .page(page)
    .per(per)
  }
  
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :user_profile
  accepts_nested_attributes_for :user_profile, reject_if: :all_blank

  validates :first_name, presence: true, length: { minimum: 3 }, on: :update

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
end

app/models/user_statistic.rb
class UserStatistic < ApplicationRecord
  belongs_to :user

  # Virtual attributes
  def total_questions
    self.correct_questions + self.incorrect_questions
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout 'admins_backoffice'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    layout :layout_by_resource

    protected

    def layout_by_resource
        if devise_controller?
            "#{resource_class.to_s.downcase}_devise"
        else
            "application"
        end
    end

    private

end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
    before_action :authenticate_user!
    layout 'users_backoffice'
end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController
    layout 'website'
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
    def translate_attribute(object = nil, method = nil)
        if object && method
            object.model.human_attribute_name(method)
        else
            '--'
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_svg(name)
    File.open("app/assets/icons/#{name}.svg", "rb") do |file|
      raw file.read
    end
  end
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
    def avatar_url
        avatar = current_user.user_profile.avatar
        avatar.attached? ? avatar : 'placeholder-avatar.jpg'
    end
end

app/helpers/website/answer_helper.rb
module Website::AnswerHelper
end

app/helpers/website/search_helper.rb
module Website::SearchHelper
end

app/helpers/website/welcome_helper.rb
module Website::WelcomeHelper
end

app/helpers/website_helper.rb
module WebsiteHelper
end

app/views/admins_backoffice/admins/shared/_form.html.erb
<h3><%= action_message %></h3>

<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to 'Página inicial', admins_backoffice_welcome_index_path  %>
    </li>    
    <li class="breadcrumb-item">
        <%= link_to 'Administradores', admins_backoffice_admins_path  %>
    </li>
    <li class="breadcrumb-item active" aria-current="page"><%= action_message %></li>
  </ol>
</nav>

<% if @admin.errors.any? %>
    <div id="errorToast" class="toast align-items-center text-bg-danger border-0 my-3" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body">
            <ul class="mb-0">
                <%= @admin.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
<% end %>

<% if @admin.errors.any? %>
    <div id="errorToast" class="toast align-items-center text-bg-danger border-0 my-3" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body">
            <ul class="mb-0">
                <%= @admin.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
<% end %>

<%= form_with(model: [ :admins_backoffice, @admin ], local: true) do |form| %>
    <div class="container p-0">

        <div class="mb-3">
            <%= form.label :email, class: "form-label fw-bold" %>
            <%= form.text_field :email, class: "form-control", placeholder: "E-mail do administrador" %>
        </div>

        <div class="mb-3">
            <%= form.label :password, class: "form-label fw-bold" %>
            <%= form.password_field :password, class: "form-control", placeholder: "********" %>
        </div>

        <div class="mb-3">
            <%= form.label :password_confirmation, class: "form-label fw-bold" %>
            <%= form.password_field :password_confirmation, class: "form-control", placeholder: "********" %>
        </div>

        <button class="btn btn-custom">
            <%= render_svg('send') %> Salvar
        </button>
    </div>
<% end %>

app/views/layouts/shared/_header.html.erb
<header class="bg-light">
    <div class="container py-2 d-flex justify-content-between align-items-center">
        <%= link_to 'Time to Answer', root_path, class: 'navbar-brand' %>
        
        <% if user_signed_in? %>
        <%= form_with(url: website_search_path, local: true, method: :get, class: 'd-flex gap-1' ) do |form| %>
            <%= form.text_field :term, class: 'form-control', placeholder: 'Pesquisar' %>
            <button class="btn btn-custom">
            <%= render_svg('search') %>
            </button>
        <%  end %>

        <div class="dropdown">
            <span class="dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user&.email %>
            </span>
            <ul class="dropdown-menu dropdown-menu-end">
            <li>
                <%= link_to users_backoffice_welcome_index_path, :class => "dropdown-item #{params[:controller] == 'users_backoffice/welcome' ? 'disabled' : ''}" do %>
                <%= render_svg('group') %>
                Perfil
                <% end %>
            </li>
            <li>
                <%= link_to users_backoffice_profile_path, :class => "dropdown-item #{params[:controller] == 'users_backoffice/profile' ? 'disabled' : ''}" do %>
                <%= render_svg('group') %>
                Editar perfil
                <% end %>
            </li>
            <li>
                <%= link_to destroy_user_session_path, method: :delete, :class => "dropdown-item" do %>
                <%= render_svg('logout') %>
                Sair
                <% end %>
            </li>
            </ul>
        </div>
        <% end %>
    </div>
</header>